USE MASTER 
IF EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='VENTAS')
DROP DATABASE VENTAS
CREATE DATABASE VENTAS
USE VENTAS

	CREATE TABLE TIPOS_USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	NOM_TIPO VARCHAR(255) UNIQUE,)

	CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	USUARIO VARCHAR(255) UNIQUE,
	PASS VARCHAR(16),
	ID_TIPO INT REFERENCES TIPOS_USUARIO(ID),)

	INSERT INTO TIPOS_USUARIO ("NOM_TIPO") VALUES ('ADMINISTRADOR')
	INSERT INTO TIPOS_USUARIO ("NOM_TIPO") VALUES ('CLIENTE')

	INSERT INTO USUARIO (USUARIO, PASS, ID_TIPO )VALUES('admin','1234',1)
	INSERT INTO USUARIO (USUARIO, PASS, ID_TIPO )VALUES('cliente','1234',2)

	CREATE PROCEDURE spAccesoSistema
	(
		@prmUser varchar(50),
		@prmPass varchar(16)
	)
	AS
		BEGIN
			SELECT U.ID, U.USUARIO, T.NOM_TIPO
			FROM USUARIO U, TIPOS_USUARIO T 
			WHERE U.ID_TIPO = T.ID AND U.USUARIO=@prmUser and U.PASS=@prmPass
		END
